In [148]:
import numpy as np
import pandas as pd
df=pd.read_csv('task_1_house_prediction_price.csv')
df

Area  BHK  Bathroom      Furnishing  \
0       800.0    3       2.0  Semi-Furnished   
1       750.0    2       2.0  Semi-Furnished   
2       950.0    2       2.0       Furnished   
3       600.0    2       2.0  Semi-Furnished   
4       650.0    2       2.0  Semi-Furnished   
...       ...  ...       ...             ...   
1254   4118.0    4       5.0     Unfurnished   
1255   1050.0    3       2.0  Semi-Furnished   
1256    875.0    3       3.0  Semi-Furnished   
1257    990.0    2       2.0     Unfurnished   
1258  11050.0    3       3.0     Unfurnished   

                                               Locality  Parking     Price  \
0                                      Rohini Sector 25      1.0   6500000   
1                J R Designers Floors, Rohini Sector 24      1.0   5000000   
2                   Citizen Apartment, Rohini Sector 13      1.0  15500000   
3                                      Rohini Sector 24      1.0   4200000   
4     Rohini Sector 24 carpet area 650 sqft status R...      1.0   6200000   
...                                                 ...      ...       ...   
1254                                  Chittaranjan Park      3.0  55000000   
1255                                  Chittaranjan Park      3.0  12500000   
1256                                  Chittaranjan Park      3.0  17500000   
1257                          Chittaranjan Park Block A      1.0  11500000   
1258                                  Chittaranjan Park      1.0  18500000   

             Status   Transaction           Type  Per_Sqft  
0     Ready_to_move  New_Property  Builder_Floor       NaN  
1     Ready_to_move  New_Property      Apartment    6667.0  
2     Ready_to_move        Resale      Apartment    6667.0  
3     Ready_to_move        Resale  Builder_Floor    6667.0  
4     Ready_to_move  New_Property  Builder_Floor    6667.0  
...             ...           ...            ...       ...  
1254  Ready_to_move  New_Property  Builder_Floor   12916.0  
1255  Ready_to_move        Resale  Builder_Floor   12916.0  
1256  Ready_to_move  New_Property  Builder_Floor   12916.0  
1257  Ready_to_move        Resale  Builder_Floor   12916.0  
1258  Ready_to_move  New_Property  Builder_Floor   12916.0  

[1259 rows x 11 columns]

In [188]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1257 entries, 0 to 1258
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Area         1257 non-null   float64
 1   BHK          1257 non-null   int64  
 2   Bathroom     1257 non-null   int32  
 3   Furnishing   1252 non-null   object 
 4   Locality     1257 non-null   object 
 5   Parking      1226 non-null   float64
 6   Price        1257 non-null   int64  
 7   Status       1257 non-null   object 
 8   Transaction  1257 non-null   object 
 9   Type         1252 non-null   object 
 10  Per_Sqft     1018 non-null   float64
dtypes: float64(3), int32(1), int64(2), object(5)
memory usage: 112.9+ KB


In [189]:
df=df.dropna(subset=['BHK'])

In [190]:
df=df.dropna(subset=['Bathroom'])

In [191]:
#Making the Machine Learning Model to predict the house prices
#The Machine learning model can be made my using any of the regression method-
#i)Linear Regression
#ii)Logistic Regression
#iii)Polynomial Regression
#......etc
#Task is asking to make the machine learning model using Linear regression

In [192]:
x=df.iloc[:,1:3].values
x

array([[3, 2],
       [2, 2],
       [2, 2],
       ...,
       [3, 3],
       [2, 2],
       [3, 3]], dtype=int64)

In [193]:
y=df.iloc[:,6].values
y

array([ 6500000,  5000000, 15500000, ..., 17500000, 11500000, 18500000],
      dtype=int64)

In [194]:
#Machine Learning Model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 0)
model=LinearRegression()

In [195]:
model.fit(x_train,y_train)

LinearRegression()

In [196]:
#Predicting the output
y_pred=model.predict(x_test)
y_pred#PREDICTED VALUES

array([30042710.57028824, 12293156.14816627, 28951897.17976945,
       28951897.17976945, 11202342.75764747, 28951897.17976945,
       12293156.14816627, -5456398.27395572, 12293156.14816627,
       46701451.60189144, 12293156.14816627, 28951897.17976945,
       12293156.14816627, 10111529.36712868, 11202342.75764747,
       28951897.17976945, 28951897.17976945, 11202342.75764747,
       12293156.14816627, 13383969.53868505, 28951897.17976945,
       11202342.75764747, 28951897.17976945, 64451006.02401343,
       28951897.17976945, 12293156.14816627, 11202342.75764747,
       -6547211.66447451, -6547211.66447451, 12293156.14816627,
       32224337.35132582, 28951897.17976945, 12293156.14816627,
       28951897.17976945, 46701451.60189144, -6547211.66447451,
       63360192.63349463, 11202342.75764747, 12293156.14816627,
       12293156.14816627, 46701451.60189144, 11202342.75764747,
       46701451.60189144, 12293156.14816627, -6547211.66447451,
       11202342.75764747, 12293156.14816

In [197]:
y_test#ACTUAL VALUES

array([ 15500000,   5510000,  22000000,  15000000,   2800000,  25000000,
         4500000,   7500000,   7000000,  87500000,  13100000,  19500000,
        20000000,   7000000,  12500000,   9500000,   8500000,  16500000,
        14800000,  17400000,  12000000,  14600000,  24000000,  51000000,
        19000000,   4620000,  18500000,   1000000,   8000000,  15000000,
         5100000,   4500000,  19000000,  26000000,  30000000,   2000000,
        65000000,  18000000,   4620000,   6000000,  47500000,  12700000,
        27500000,  13500000,   3000000,   5000000,   7020000,  23500000,
        25000000,  33500000,   6000000, 220000000,   4500000,  14600000,
        17200000,   5000000,  13500000,  80000000,  30000000,   4000000,
         5650000,   2500000,  16500000,   1500000,   3100000,  74500000,
         8000000,   3000000,  14500000,   6000000,   1400000,  13000000,
         5900000,   3310000,  16500000,  19000000,  35000000,   3800000,
        93000000,  13200000,  50000000,   6000000, 

In [198]:
#Indivisual Prediction for any input.
model.predict([[1,2]])

array([10111529.36712868])

In [199]:
model.predict([[2,2]])

array([11202342.75764747])

In [200]:
model.predict([[3,2]])

array([12293156.14816627])

In [204]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_test,y_pred)
accuracy#The accuracy of this machine learning model is 0.46.

0.4608044420841291