In [100]:
import pandas as pd
import numpy as np
df=pd.read_csv('task_2_Wine_Quality_Prediction.csv')
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1138            6.3             0.510         0.13             2.3      0.076   
1139            6.8             0.620         0.08             1.9      0.068   
1140            6.2             0.600         0.08             2.0      0.090   
1141            5.9             0.550         0.10             2.2      0.062   
1142            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1138                 29.0                  40.0  0.99574  3.42       0.75   
1139                 28.0                  38.0  0.99651  3.42       0.82   
1140                 32.0                  44.0  0.99490  3.45       0.58   
1141                 39.0                  51.0  0.99512  3.52       0.76   
1142                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  quality    Id  
0         9.4        5     0  
1         9.8        5     1  
2         9.8        5     2  
3         9.8        6     3  
4         9.4        5     4  
...       ...      ...   ...  
1138     11.0        6  1592  
1139      9.5        6  1593  
1140     10.5        5  1594  
1141     11.2        6  1595  
1142     10.2        5  1597  

[1143 rows x 13 columns]

In [101]:
#Removing all the null values(if present)from each and every column.

In [102]:
df = df.dropna(subset=['fixed acidity'])
df['fixed acidity'] = df['fixed acidity'].fillna(df['fixed acidity'].mean())

In [103]:
df = df.dropna(subset=['volatile acidity'])
df['volatile acidity'] = df['volatile acidity'].fillna(df['volatile acidity'].mean())

In [104]:
df = df.dropna(subset=['citric acid'])
df['citric acid'] = df['citric acid'].fillna(df['citric acid'].mean())

In [105]:
df = df.dropna(subset=['residual sugar'])
df['residual sugar'] = df['residual sugar'].fillna(df['residual sugar'].mean())

In [106]:
df = df.dropna(subset=['chlorides'])
df['chlorides'] = df['chlorides'].fillna(df['chlorides'].mean())

In [107]:
df = df.dropna(subset=['free sulfur dioxide'])
df['free sulfur dioxide'] = df['free sulfur dioxide'].fillna(df['free sulfur dioxide'].mean())

In [108]:
df = df.dropna(subset=['density'])
df['density'] = df['density'].fillna(df['density'].mean())

In [109]:
df = df.dropna(subset=['pH'])
df['pH'] = df['pH'].fillna(df['pH'].mean())

In [110]:
df = df.dropna(subset=['sulphates'])
df['sulphates'] = df['sulphates'].fillna(df['sulphates'].mean())

In [111]:
df = df.dropna(subset=['alcohol'])
df['alcohol'] = df['alcohol'].fillna(df['alcohol'].mean())

In [112]:
df = df.dropna(subset=['quality'])
df['quality'] = df['quality'].fillna(df['quality'].mean())

In [113]:
df = df.dropna(subset=['Id'])
df['Id'] = df['Id'].fillna(df['Id'].mean())

In [114]:
#Making the Machine Learning Model to predict the house prices
#The Machine learning model can be made my using any of the regression method-
#i)Linear Regression
#ii)Logistic Regression
#iii)Polynomial Regression
#......etc
#Task is asking to make the machine learning model using Linear regression

In [115]:
x=df.iloc[:,1:3].values
x

array([[0.7  , 0.   ],
       [0.88 , 0.   ],
       [0.76 , 0.04 ],
       ...,
       [0.6  , 0.08 ],
       [0.55 , 0.1  ],
       [0.645, 0.12 ]])

In [116]:
y=df.iloc[:,11].values
y

array([5, 5, 5, ..., 5, 6, 5], dtype=int64)

In [122]:
#Machine Learning Model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state = 0)
model=LinearRegression()

In [123]:
model.fit(x_train,y_train)

LinearRegression()

In [124]:
#Predict the output
y_pred = model.predict(x_test) #using the input testing values , we predict the output
y_pred #PREDICTED VALUES

array([5.22273365, 4.64544073, 5.27703563, 5.17174254, 5.93415669,
       5.85494164, 5.9220578 , 5.9808764 , 5.63329892, 6.13397236,
       5.02741421, 5.95549326, 5.19166892, 5.40797749, 5.4962054 ,
       5.1126787 , 5.54376303, 5.79291439, 5.56035815, 5.10154035,
       6.31245145, 5.30325669, 5.56238143, 5.97613494, 5.28179749,
       5.73503591, 5.70397118, 5.9808764 , 5.57067899, 5.6410038 ,
       5.7958778 , 5.54292512, 5.77750464, 6.07811717, 6.06483292,
       5.30515735, 5.4037061 , 5.78555696, 5.6360171 , 5.36706198,
       5.56949362, 5.65962219, 5.61147188, 5.94778839, 5.4187684 ,
       5.62534881, 5.70540178, 5.9658141 , 6.17002379, 5.52514463,
       5.45884599, 5.47307037, 5.85647445, 5.9994948 , 5.84876958,
       5.4324001 , 5.34143361, 5.90793563, 4.85913334, 5.56890094,
       5.50865174, 5.54233243, 5.97020812, 5.5399617 , 5.34488749,
       5.69187229, 5.98917396, 5.23090859, 5.47141494, 5.56178875,
       5.37595223, 5.59403885, 5.43620143, 5.77286539, 5.65819

In [125]:
y_test

array([5, 4, 6, 6, 5, 6, 5, 6, 6, 7, 5, 6, 6, 5, 6, 6, 6, 6, 5, 5, 6, 5,
       7, 6, 5, 5, 5, 6, 6, 5, 6, 5, 5, 6, 5, 6, 6, 4, 5, 6, 5, 6, 6, 6,
       5, 5, 5, 7, 8, 6, 6, 5, 5, 7, 5, 5, 5, 5, 5, 6, 6, 5, 6, 5, 6, 5,
       6, 5, 5, 7, 5, 5, 6, 7, 6, 7, 6, 7, 5, 7, 5, 5, 6, 5, 6, 6, 6, 5,
       5, 7, 6, 7, 4, 5, 6, 6, 5, 5, 5, 5, 3, 5, 8, 5, 6, 6, 6, 6, 5, 5,
       5, 5, 5, 7, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 6, 6, 6, 7, 5, 6, 7, 6,
       6, 5, 6, 6, 5, 6, 6, 5, 5, 6, 6, 7, 5, 5, 6, 7, 6, 5, 5, 6, 6, 6,
       5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 7, 7, 7, 6, 5, 4, 5, 7, 6, 6,
       6, 5, 5, 6, 5, 5, 5, 5, 5, 6, 5, 4, 4, 5, 7, 5, 5, 6, 6, 5, 5, 6,
       6, 6, 5, 6, 4, 7, 7, 7, 5, 5, 5, 5, 6, 6, 6, 7, 5, 5, 6, 6, 5, 7,
       6, 6, 6, 5, 5, 6, 7, 5, 5, 5, 6, 7, 5, 6, 6, 6, 6, 5, 5, 6, 7, 5,
       6, 6, 6, 5, 6, 5, 7, 5, 6, 7, 5, 5, 6, 6, 5, 6, 6, 5, 5, 6, 5, 6,
       6, 6, 5, 5, 5, 6, 6, 5, 6, 5, 6, 5, 7, 5, 7, 6, 6, 5, 6, 5, 7, 5],
      dtype=int64)

In [127]:
#Indivisual Prediction for any input.
model.predict([[0.700,0.00]])

array([5.34488749])

In [128]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_test,y_pred)
accuracy#The error in the machine model is 0.1889

0.1889606780994889